import fs from 'node:fs';
const K = JSON.parse(fs.readFileSync(new URL('keys.json', import.meta.url))); const U = 'http://127.0.0.1:8787/addins-api/';
const ctx = 'Sheet: Sales. The formula goes in cell H2.\nColumns:\n  B = Party (text)\n  E = Amount (number)\n';
const post = async (path, body, headers = {}) => { const r = await fetch(U + path, { method: 'POST', headers: Object.assign({ 'Content-Type': 'application/json' }, headers), body: JSON.stringify(body) }); return [r.status, await r.json()]; };
const ai = (key, request = 'total amount for this party') => post('ai/formula', { key, request, context: ctx });
const wait = (ms) => new Promise(r => setTimeout(r, ms));
let fails = 0; const check = (name, ok, got) => { if (!ok) fails++; console.log((ok ? 'ok   ' : 'FAIL ') + name + '  ' + JSON.stringify(got)); };
let [s, j] = await ai(K.pro.key); check('pro key gets a formula', s === 200 && j.formula === '=SUMIFS($E$2:$E$1301,$B$2:$B$1301,B2)' && j.tier === 'Pro' && j.left === 99, [s, j]);
[s, j] = await ai(K.pro.key); check('second request within 4 s is slowed', s === 429 && j.code === 'rate', [s, j.code]);
await wait(4500);
[s, j] = await ai(K.free.key); check('free key: 2 a day (set by AI_FREE_PER_DAY)', s === 200 && j.left === 1 && j.tier === 'Free', [s, j.left]);
await wait(4500); [s, j] = await ai(K.free.key); check('free key second', s === 200 && j.left === 0, [s, j.left]);
await wait(4500); [s, j] = await ai(K.free.key); check('free key over the limit, with the Pro offer', s === 429 && j.code === 'limit' && /Pro you get 100/.test(j.error), [s, j.error]);
[s, j] = await ai(K.expired.key); check('expired Pro key refused', s === 402 && j.code === 'expired', [s, j.error]);
[s, j] = await ai('DBK1-AAAAA-BBBBB'); check('not a key refused', s === 401 && j.code === 'no_key', [s, j.code]);
let bad = K.pro.key.slice(0, -3) + (K.pro.key.endsWith('Z') ? 'Y' : 'Z') + K.pro.key.slice(-2); [s, j] = await ai(bad); check('changed key refused', s === 401, [s, j.code]);
[s, j] = await post('ai/block', { id: K.blocked.id }); check('block needs the admin key', s === 401, [s]);
[s, j] = await post('ai/block', { id: K.blocked.id }, { Authorization: 'Bearer admin-key-for-local-test-only-1234' }); check('admin blocks a key', s === 200 && j.blocked, [s, j]);
await wait(500); [s, j] = await ai(K.blocked.key); check('blocked key refused', s === 403 && j.code === 'blocked', [s, j.code]);
[s, j] = await post('ai/formula', { key: K.pro.key, request: 'x'.repeat(20000), context: ctx }); check('oversized request refused', s === 413, [s]);
[s, j] = await post('ai/formula', { key: K.pro.key, request: 'hi', context: ctx }, { Origin: 'https://evil.example' }); check('other web sites refused', s === 403 && j.code === 'origin', [s]);
const r = await fetch(U + 'ai/usage', { headers: { Authorization: 'Bearer admin-key-for-local-test-only-1234' } }); j = await r.json(); check('admin usage report', r.status === 200 && j.requests === 3 && j.keys === 2, j);
const up = fs.readFileSync(new URL('upstream.log', import.meta.url), 'utf8').trim().split('\n').map(JSON.parse);
check('upstream called once per answered request', up.length === 3, up.length);
const u0 = up[0];
check('upstream: site key, model, low effort, fallback, fixed system prompt', u0.headers['x-api-key'] === 'test-key' && u0.body.model === 'claude-opus-5-5' && u0.body.output_config.effort === 'low' && u0.body.fallbacks === 'default' && /server-side-fallback-2026-07-01/.test(u0.headers['anthropic-beta']) && /Excel formulas/.test(u0.body.system) && u0.body.max_tokens === 4000, { model: u0.body.model, beta: u0.headers['anthropic-beta'], effort: u0.body.output_config });
console.log(fails ? fails + ' FAILED' : 'ALL PASSED');
